[0m[[0m[31merror[0m] [0m[0mD:\Users\lucas\scalable.services\datalog\src\main\scala\services\scalable\datalog\DatomDatabase.scala:56:3: not found: value c[0m
[0m[[0m[31merror[0m] [0m[0m  c[0m
[0m[[0m[31merror[0m] [0m[0m  ^[0m
[0m[[0m[31merror[0m] [0m[0mD:\Users\lucas\scalable.services\datalog\src\main\scala\services\scalable\datalog\DatomDatabase.scala:86:130: not found: value aevtOrdering[0m
[0m[[0m[31merror[0m] [0m[0mError occurred in an application involving default arguments.[0m
[0m[[0m[31merror[0m] [0m[0m  val aevtCtx = new DefaultContext[Datom, Bytes](s"$indexId-aevt", None, NUM_LEAF_ENTRIES, NUM_META_ENTRIES)(ec, storage, cache, aevtOrdering)[0m
[0m[[0m[31merror[0m] [0m[0m                                                                                                                                 ^[0m
[0m[[0m[31merror[0m] [0m[0mD:\Users\lucas\scalable.services\datalog\src\main\scala\services\scalable\datalog\DatomDatabase.scala:87:67: not found: value aevtOrdering[0m
[0m[[0m[31merror[0m] [0m[0m  val aevtIndex = new QueryableIndex[Datom, Bytes]()(ec, aevtCtx, aevtOrdering)[0m
[0m[[0m[31merror[0m] [0m[0m                                                                  ^[0m
[0m[[0m[31merror[0m] [0m[0mD:\Users\lucas\scalable.services\datalog\src\main\scala\services\scalable\datalog\DatomDatabase.scala:98:36: not found: value aevtOrdering[0m
[0m[[0m[31merror[0m] [0m[0m      r2 <- aevtIndex.insert(data)(aevtOrdering).flatMap(_ => aevtCtx.save())[0m
[0m[[0m[31merror[0m] [0m[0m                                   ^[0m
[0m[[0m[31merror[0m] [0m[0mfour errors found[0m
